# This file basically stores the configuration settings of my project in a structured and human
# readable format.

artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/GENTLEW1ND/PriceSpeculator/raw/refs/heads/main/mobiles-dataset-2025.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    unzip_data_dir: artifacts/data_ingestion/Mobiles Dataset (2025).csv
    STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
    root_dir: artifacts/data_transformation
    unzip_data_dir: artifacts/data_ingestion/Mobiles Dataset (2025).csv

model_trainer:
    root_dir: artifacts/model_trainer
    train_data_path: artifacts/data_transformation/train.csv
    test_data_path: artifacts/data_transformation/test.csv
    model_name: model.joblib