# This file basically stores the configuration settings of my project in a structured and human
# readable format.

artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/GENTLEW1ND/PriceSpeculator/raw/refs/heads/main/mobiles-dataset-2025.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion